# golangci-lint 配置
run:
  timeout: 10m
  tests: false
  modules-download-mode: mod
  skip-dirs:
    - vendor
    - .git

linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - gosimple
    - ineffassign
  disable:
    - errcheck
    - unused
    - revive
    - gocyclo
    - goconst
    - gocritic
    - gosec
    - unconvert
    - unparam
    - whitespace
    - stylecheck
    - exportloopref
    - misspell
    - goimports

linters-settings:
  staticcheck:
    checks: ["all", "-SA1019", "-SA4006"]
  govet:
    enable-all: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - linters:
        - govet
      text: "shadow"
  max-issues-per-linter: 100
  max-same-issues: 20

